
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver import ActionChains
import time
import pytest



@pytest.fixture()
def test_setup():
    global driver
    driver = webdriver.Chrome('/Users/oeygu/Downloads/chromedriver') ##Change this tho your location of the web driver
    driver.get("https://www.givelify.com/donate/anointed-city-of-the-lord-indianapolis-in-2j7wy5OTA=/donation/amount")
    driver.maximize_window()
    yield
    driver.close()
    driver.quit()


def test_Invalid_Email_Account(test_setup):
    actionChains = ActionChains(driver)
    signInBtn = driver.find_element(By.XPATH, '//a[@class="sc-iIUQWv dYoXaJ menu-list-icon"]')
    actionChains.click(signInBtn).perform()
    driver.implicitly_wait(2)
    joinGivelifyTab = driver.find_element(By.XPATH, '//a[@class="sc-lgarKF fuXnSU"]')
    actionChains.click(joinGivelifyTab).perform()
    driver.implicitly_wait(2)
    fullNameTextView = driver.find_element(By.XPATH, '//input[@id="fullname"]')
    actionChains.scroll_to_element(fullNameTextView).perform()
    actionChains.click(fullNameTextView).perform()
    actionChains.send_keys_to_element(fullNameTextView, "Osman Eygu").perform()
    driver.implicitly_wait(1)
    emailAddressTextview = driver.find_element(By.XPATH, '//input[@id="email"]')
    actionChains.scroll_to_element(emailAddressTextview).perform()
    actionChains.click(emailAddressTextview).perform()
    actionChains.send_keys_to_element(emailAddressTextview, "Osman Eygu").perform()
    driver.implicitly_wait(2)
    actionChains.scroll_to_element(fullNameTextView).perform()
    actionChains.click(fullNameTextView).perform()
    driver.implicitly_wait(10)
    invalidEmailText = driver.find_element(By.XPATH, '//span[normalize-space()="*This field must be an email"]')
    assert invalidEmailText.text == "*This field must be an email", "Code doesn't match with the response"


def test_Join_Account(test_setup):
    actionChains = ActionChains(driver)
    signInBtn = driver.find_element(By.XPATH, '//a[@class="sc-iIUQWv dYoXaJ menu-list-icon"]')
    actionChains.click(signInBtn).perform()
    driver.implicitly_wait(3)
    joinGivelifyTab = driver.find_element(By.XPATH, '//a[@class="sc-lgarKF fuXnSU"]')
    actionChains.click(joinGivelifyTab).perform()
    driver.implicitly_wait(3)
    fullNameTextView = driver.find_element(By.XPATH, '//input[@id="fullname"]')
    actionChains.scroll_to_element(fullNameTextView).perform()
    actionChains.click(fullNameTextView).perform()
    actionChains.send_keys_to_element(fullNameTextView, "Osman Eygu").perform()
    driver.implicitly_wait(3)
    emailAddressTextview = driver.find_element(By.XPATH, '//input[@id="email"]')
    actionChains.scroll_to_element(emailAddressTextview).perform()
    actionChains.click(emailAddressTextview).perform()
    actionChains.send_keys_to_element(emailAddressTextview, "eyguosman515@gmail.com").perform()
    driver.implicitly_wait(3)
    passwordTextView = driver.find_element(By.XPATH, '//input[@id="password"]')
    actionChains.scroll_to_element(passwordTextView).perform()
    actionChains.click(passwordTextView).perform()
    actionChains.send_keys_to_element(passwordTextView, "Osman1234").perform()
    driver.implicitly_wait(3)
    passwordConfirmationTextView = driver.find_element(By.XPATH, '//input[@id="confirmpassword"]')
    actionChains.scroll_to_element(passwordConfirmationTextView).perform()
    actionChains.click(passwordConfirmationTextView).perform()
    actionChains.send_keys_to_element(passwordConfirmationTextView, "Osman1234").perform()
    driver.implicitly_wait(2)
    joinGivelifyBtn = driver.find_element(By.XPATH, '//div[@class="sc-hLVXRe euqDdi"]')
    actionChains.scroll_to_element(joinGivelifyBtn).perform()
    actionChains.click(joinGivelifyBtn).perform()
    driver.implicitly_wait(15)
    accountValidation = driver.find_element(By.XPATH, '//span[@class="sc-hiCibw eMiLOR username"]')
    driver.implicitly_wait(30)
    assert accountValidation.text == "Osman Eygu", "Account was not verified"
    driver.implicitly_wait(10)
    selectYourGift = driver.find_element(By.XPATH, '//h2[normalize-space()="Select your gift"]')
    actionChains.click(selectYourGift).perform()


def test_Success_Login(test_setup):
    actionChains = ActionChains(driver)
    signInBtn = driver.find_element(By.XPATH, '//a[@class="sc-iIUQWv dYoXaJ menu-list-icon"]')
    actionChains.click(signInBtn).perform()
    driver.implicitly_wait(3)
    signInTab = driver.find_element(By.XPATH, '//span[@class="sc-hiCibw kjYGtI sc-BHvUt fJlZte"]')
    actionChains.click(signInTab).perform()
    driver.implicitly_wait(3)
    emailAddressField = driver.find_element(By.XPATH, '//input[@type="email"]')
    actionChains.scroll_to_element(emailAddressField).perform()
    actionChains.click(emailAddressField).perform()
    actionChains.send_keys_to_element(emailAddressField, "eyguosman@gmail.com")
    driver.implicitly_wait(3)
    passwordField = driver.find_element(By.XPATH, '//input[@type="password"]')
    actionChains.scroll_to_element(passwordField).perform()
    actionChains.click(passwordField).perform()
    actionChains.send_keys_to_element(passwordField, "Osman1234").perform()
    driver.implicitly_wait(3)
    signInBtnField = driver.find_element(By.XPATH, '//div[@class="sc-hKTqa gwQhCo"]')
    actionChains.scroll_to_element(signInBtnField).perform()
    actionChains.click(signInBtnField).perform()
    driver.implicitly_wait(15)
    accountValidation = driver.find_element(By.XPATH, '//span[@class="sc-hiCibw eMiLOR username"]')
    driver.implicitly_wait(15)
    assert accountValidation.text == "Osman Eygu", "Account was not verified"
    driver.implicitly_wait(10)
    selectYourGift = driver.find_element(By.XPATH, '//h2[normalize-space()="Select your gift"]')
    actionChains.click(selectYourGift).perform()

def test_InvalidEmail_Valid_Password (test_setup):
    actionChains = ActionChains(driver)
    signInBtn = driver.find_element(By.XPATH, '//a[@class="sc-iIUQWv dYoXaJ menu-list-icon"]')
    actionChains.click(signInBtn).perform()
    driver.implicitly_wait(3)
    signInTab = driver.find_element(By.XPATH, '//span[@class="sc-hiCibw kjYGtI sc-BHvUt fJlZte"]')
    actionChains.click(signInTab).perform()
    driver.implicitly_wait(3)
    emailAddressField = driver.find_element(By.XPATH, '//input[@type="email"]')
    actionChains.scroll_to_element(emailAddressField).perform()
    actionChains.click(emailAddressField).perform()
    actionChains.send_keys_to_element(emailAddressField, "eyguosman511@gmail.com")
    driver.implicitly_wait(3)
    passwordField = driver.find_element(By.XPATH, '//input[@type="password"]')
    actionChains.scroll_to_element(passwordField).perform()
    actionChains.click(passwordField).perform()
    actionChains.send_keys_to_element(passwordField, "Osman1234").perform()
    driver.implicitly_wait(3)
    signInBtnField = driver.find_element(By.XPATH, '//div[@class="sc-hKTqa gwQhCo"]')
    actionChains.scroll_to_element(signInBtnField).perform()
    actionChains.click(signInBtnField).perform()
    driver.implicitly_wait(15)
    invalidAccountTextField = driver.find_element(By.XPATH, '//span[@class="sc-hiCibw lhPOko"]//div[2]')
    assert invalidAccountTextField.text == "Check the email address/password and try again. If you don't have an account to give on Givelify, you can sign up by pressing Join Givelify." , "Not warning message shown"
    driver.implicitly_wait(15)
    actionChains.click(invalidAccountTextField).perform()

def test_ValidEmail_Invalid_Password (test_setup):
    actionChains = ActionChains(driver)
    signInBtn = driver.find_element(By.XPATH, '//a[@class="sc-iIUQWv dYoXaJ menu-list-icon"]')
    actionChains.click(signInBtn).perform()
    driver.implicitly_wait(3)
    signInTab = driver.find_element(By.XPATH, '//span[@class="sc-hiCibw kjYGtI sc-BHvUt fJlZte"]')
    actionChains.click(signInTab).perform()
    driver.implicitly_wait(3)
    emailAddressField = driver.find_element(By.XPATH, '//input[@type="email"]')
    actionChains.scroll_to_element(emailAddressField).perform()
    actionChains.click(emailAddressField).perform()
    actionChains.send_keys_to_element(emailAddressField, "eyguosman@gmail.com")
    driver.implicitly_wait(3)
    passwordField = driver.find_element(By.XPATH, '//input[@type="password"]')
    actionChains.scroll_to_element(passwordField).perform()
    actionChains.click(passwordField).perform()
    actionChains.send_keys_to_element(passwordField, "Osman12345").perform()
    driver.implicitly_wait(3)
    signInBtnField = driver.find_element(By.XPATH, '//div[@class="sc-hKTqa gwQhCo"]')
    actionChains.scroll_to_element(signInBtnField).perform()
    actionChains.click(signInBtnField).perform()
    driver.implicitly_wait(15)
    invalidAccountTextField = driver.find_element(By.XPATH, '//span[@class="sc-hiCibw lhPOko"]//div[2]')
    assert invalidAccountTextField.text == "Check the email address/password and try again. If you don't have an account to give on Givelify, you can sign up by pressing Join Givelify." , "Not warning message shown"
    driver.implicitly_wait(15)
    actionChains.click(invalidAccountTextField).perform()

def test_Forgot_Password_Is_Shown (test_setup):
    actionChains = ActionChains(driver)
    signInBtn = driver.find_element(By.XPATH, '//a[@class="sc-iIUQWv dYoXaJ menu-list-icon"]')
    actionChains.click(signInBtn).perform()
    driver.implicitly_wait(3)
    signInTab = driver.find_element(By.XPATH, '//span[@class="sc-hiCibw kjYGtI sc-BHvUt fJlZte"]')
    actionChains.click(signInTab).perform()
    driver.implicitly_wait(3)
    forgotPasswordText = driver.find_element(By.XPATH, '//span[@class="sc-hiCibw kVoTyY poiter mt-10 dib"]')
    actionChains.scroll_to_element(forgotPasswordText).perform()
    actionChains.click(forgotPasswordText).perform()
    driver.implicitly_wait(15)
    recoverPasswordPopUp = driver.find_element(By.XPATH, '//div[@role="dialog"]')
    actionChains.click(recoverPasswordPopUp).perform()
    assert recoverPasswordPopUp.is_displayed() , "No Recover Password Pop Up is Displayed"

def test_Forgot_Password_Invalid_Email_Error_Shown (test_setup):
    actionChains = ActionChains(driver)
    signInBtn = driver.find_element(By.XPATH, '//a[@class="sc-iIUQWv dYoXaJ menu-list-icon"]')
    actionChains.click(signInBtn).perform()
    driver.implicitly_wait(3)
    signInTab = driver.find_element(By.XPATH, '//span[@class="sc-hiCibw kjYGtI sc-BHvUt fJlZte"]')
    actionChains.click(signInTab).perform()
    driver.implicitly_wait(3)
    forgotPasswordText = driver.find_element(By.XPATH, '//span[@class="sc-hiCibw kVoTyY poiter mt-10 dib"]')
    actionChains.scroll_to_element(forgotPasswordText).perform()
    actionChains.click(forgotPasswordText).perform()
    driver.implicitly_wait(5)
    recoverPasswordPopUp = driver.find_element(By.XPATH, '//div[@role="dialog"]')
    actionChains.click(recoverPasswordPopUp).perform()
    driver.implicitly_wait(5)
    recoverEmailField = driver.find_element(By.XPATH, '//input[@placeholder="Email"]')
    actionChains.click(recoverEmailField).perform()
    actionChains.send_keys_to_element(recoverEmailField, "eyguosman@gmail1123.com").perform()
    driver.implicitly_wait(3)
    resetPasswordBtn = driver.find_element(By.XPATH, '//button[normalize-space()="Reset Password"]')
    actionChains.click(resetPasswordBtn).perform()
    driver.implicitly_wait(5)
    errorInvalidEmailText = driver.find_element(By.XPATH, '//span[contains(text(),"Oops — there")]')
    assert errorInvalidEmailText.is_displayed(), "Error email text is now shown"

def test_Forgot_Password_Valid_Email (test_setup):
    actionChains = ActionChains(driver)
    signInBtn = driver.find_element(By.XPATH, '//a[@class="sc-iIUQWv dYoXaJ menu-list-icon"]')
    actionChains.click(signInBtn).perform()
    driver.implicitly_wait(3)
    signInTab = driver.find_element(By.XPATH, '//span[@class="sc-hiCibw kjYGtI sc-BHvUt fJlZte"]')
    actionChains.click(signInTab).perform()
    driver.implicitly_wait(3)
    forgotPasswordText = driver.find_element(By.XPATH, '//span[@class="sc-hiCibw kVoTyY poiter mt-10 dib"]')
    actionChains.scroll_to_element(forgotPasswordText).perform()
    actionChains.click(forgotPasswordText).perform()
    driver.implicitly_wait(5)
    recoverPasswordPopUp = driver.find_element(By.XPATH, '//div[@role="dialog"]')
    actionChains.click(recoverPasswordPopUp).perform()
    driver.implicitly_wait(5)
    recoverEmailField = driver.find_element(By.XPATH, '//input[@placeholder="Email"]')
    actionChains.click(recoverEmailField).perform()
    actionChains.send_keys_to_element(recoverEmailField, "eyguosman@gmail.com").perform()
    driver.implicitly_wait(3)
    resetPasswordBtn = driver.find_element(By.XPATH, '//button[normalize-space()="Reset Password"]')
    actionChains.click(resetPasswordBtn).perform()
    driver.implicitly_wait(15)
    resetPasswordSuccessMessage = driver.find_element(By.XPATH, '//div[@class="MuiPaper-root MuiAlert-root MuiAlert-standardSuccess MuiPaper-elevation0"]')
    driver.implicitly_wait(15)
    assert resetPasswordSuccessMessage.is_displayed(), "No success password send"
    actionChains.click(resetPasswordSuccessMessage).perform()
